### ISSUE TITLE
Usage with Docker; specifying a schema file name

### ISSUE THREAD

**Issue by lameimpala** [APIs-guru/graphql-faker#93]
Maybe I'm an idiot, but I can't get graphql-faker to pickup the schema file while running in docker.  The only workaround I found is to name the mounted schema file exactly as the default: `graphql-faker`.

**Comment by IvanGoncharov** [comment]
@lameimpala I have zero knowledge of Docker so it can be a case that I broke something.
Just to be sure, you tried this line from README?
https://github.com/APIs-guru/graphql-faker#usage-with-docker
> docker run -v=${PWD}:/workdir apisguru/graphql-faker path/to/schema.sdl

**Comment by mschipperheyn** [comment]
@IvanGoncharov I answered your question as part of a question I put https://github.com/APIs-guru/graphql-faker/issues/94

**Comment by robsontenorio** [comment]
For future reference, here is a setup for gitlab.

So `http://my-faker-server:9002/graphql` will be available on tests.

gitlab-ci.yml
```yml
phpunit:
  stage: test
  services:
    - name: apisguru/graphql-faker:latest
      alias: my-faker-server
      command: ["/builds/repo-name/path/to/schema/fake.graphql"]
  script:
    - composer test
```
