### ISSUE TITLE
Deploying on Heroku

### ISSUE THREAD

**Issue by mschipperheyn** [APIs-guru/graphql-faker#94]
Not an expert on Docker.

I managed to deploy graphql-faker to Heroku

```
heroku container:login
docker tag <IMAGEID> registry.heroku.com/ <APPNAME>/web
docker push registry.heroku.com/ <APPNAME>/web
heroku container:release web --app <APPNAME>
heroku ps:scale web=1
```
where APPNAME is the heroku app name and IMAGEID is the local graphql-faker Docker image you created with `docker-compose up -d`.

docker-compose.yml
```
version: '3.2'

services:
  graphql-faker:
    image: apisguru/graphql-faker
    ports:
      - '9002:9002'
    container_name: graphql_faker
    command: ./my-sdl-schema.sdl
    volumes:
      - ./src/apollo/remote:/workdir
```

However, my issue is deploying the sdl schema along with the image. Bc it's currently referenced locally for development but the image deploy doesn't include the schema and hence I get the default schema on Heroku.
